fix/DPP-3934: bump vulnerable dependency for CVE-2022-21223
criteo/ios-publisher-sdk pull request #242
Opened 2022-04-25 07:03 UTC by CedricGatay

Fixes DPP-3934

2022-04-25 07:04 UTC, TurpIF approved these changes

2022-05-17 10:25 UTC, CedricGatay commented
This PR is after #243

2022-05-30 07:51 UTC, TurpIF requested changes
Ok for the bump of version. But could you rebase your work on the main branch rather than having it on top of MoPub removal.

2022-05-30 07:52 UTC, TurpIF commented
Or keep it as is, but we need to merge the other PR first (and so you might to to rebase your work anyway)

2022-05-30 08:29 UTC, CedricGatay commented
The thing is that without merging the other PR, this one won't ever build (as mopub dependency is now unavailable)

2022-06-01 09:57 UTC, TurpIF submitted a review, later dismissed

2022-06-02 06:56 UTC, TurpIF approved these changes

2022-06-02 07:06 UTC, merged